name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version'     
        required: true
      body:
        description: 'Release description'
        required: true
      draft:
        description: 'is draft?'
        required: true
        default: 'true'
      prerelease:
        description: 'Is PreRelease?'
        required: true
        default: 'true'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Build
        env:
          CGO_ENABLED: 0
          DEBUG: false
        run: |
          go install -v
          GOOS=linux GOARCH=386 go build -ldflags="-s -w" -a -v -o release/rattus-linux-i386
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -a -v -o release/rattus-linux-amd64
          GOOS=freebsd GOARCH=386 go build -ldflags="-s -w" -a -v -o release/rattus-freebsd-i386
          GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -a -v -o release/rattus-freebsd-amd64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -a -v -o release/rattus-darwin-amd64
          GOOS=windows GOARCH=386 go build -ldflags="-s -w" -a -v -o release/rattus-windows-i386.exe
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -a -v -o release/rattus-windows-amd64.exe
          upx -9 --best --ultra-brute release/rattus-*
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: rattus
          path: ./release/*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.body }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
      - name: Upload Release Asset linux-i386
        id: upload-release-asset-linux-i386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./release/rattus-linux-i386
          asset_name: rattus-linux-i386
      - name: Upload Release Asset linux-amd64
        id: upload-release-asset-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./release/rattus-linux-amd64
          asset_name: rattus-linux-amd64
      - name: Upload Release Asset freebsd-i386
        id: upload-release-asset-freebsd-i386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./release/rattus-freebsd-i386
          asset_name: rattus-freebsd-i386
      - name: Upload Release Asset freebsd-amd64
        id: upload-release-asset-freebsd-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./release/rattus-freebsd-amd64
          asset_name: rattus-freebsd-amd64
